---
abstract: '#clip output to clipboard'
author:
  - 'Steve Nolte <mcsnolte@cpan.org>'
build_requires:
  File::Find: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-REPL-Plugin-Clipboard
requires:
  Clipboard: 0
  Devel::REPL::Plugin: 0
  MooseX::AttributeHelpers::Collection::Array: 0
  Term::ANSIColor: 2.01
  namespace::autoclean: 0
resources:
  repository: git://github.com/mcsnolte/Devel-REPL-Plugin-Clipboard.git
version: 0.002
